### ISSUE TITLE
单独提供一个设置token的接口

### ISSUE THREAD

**Issue by WzFFzW** [juicecube/mlz-axios#4]
初始化的时候，不一定有token（因为可能没有登录或者需要更新token的）

在调用的时候，可能需要重新设置一下token

setAuthorizationTypeOrToken这个方法，无论是实例的还是静态的，token那个应该是非必须

**Comment by Popeye-Wz** [comment]
1、初始化的时候没有token的可以先传 ''（期望用户自己知道现在没有token，期望最好在可以拿到token的时候再调用某个实例的方法或全局的静态方法来设置token）
2、支持在调用某个具体方法时以config.header的形式传入token

**Comment by DogJun** [comment]
已解决
